HDFS_HOME=.
RUN_NAME=Qwen2.5-3B-REINFORCE-Stage2

python3 openrlhf/cli/train_ppo_ray.py \
    --advantage_estimator reinforce \
    --remote_rm_url examples/scripts/r1_reward_func.py \
    --ref_num_nodes 1 \
    --ref_num_gpus_per_node 4 \
    --reward_num_nodes 0 \
    --reward_num_gpus_per_node 0 \
    --actor_num_nodes 1 \
    --actor_num_gpus_per_node 4 \
    --vllm_num_engines 2 \
    --vllm_tensor_parallel_size 2 \
    --colocate_actor_ref \
    --packing_samples \
    --pretrain pe-nlp/Qwen2.5-3B-REINFORCE-90K-3096-Step424 \
    --save_path $HDFS_HOME/checkpoints/$RUN_NAME \
    --micro_train_batch_size 2 \
    --train_batch_size 512 \
    --micro_rollout_batch_size 4 \
    --rollout_batch_size 1024 \
    --temperature 1.0 \
    --n_samples_per_prompt 1 \
    --max_samples 100000 \
    --max_epochs 1 \
    --num_episodes 15 \
    --prompt_max_len 1024 \
    --generate_max_len 8192 \
    --zero_stage 3 \
    --bf16 \
    --actor_learning_rate 1e-6 \
    --lr_warmup_ratio 0.001 \
    --init_kl_coef 0.0 \
    --prompt_data  pe-nlp/DeepScaleR-40k-Prompt-Filtered \
    --input_key input \
    --normalize_reward \
    --flash_attn \
    --adam_offload \
    --gradient_checkpointing \
    --enable_prefix_caching \
    --save_steps 8 \
    --load_checkpoint \
    --use_wandb XXX \
    --wandb_run_name $RUN_NAME \
    --ckpt_path $HDFS_HOME/checkpoints/$RUN_NAME  \
    --save_hf_ckpt \
    --max_ckpt_num 20
